<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>

    <!-- 根命名空间故意避开 .Windows 段,避免与系统 Windows.* 类型冲突 -->
    <RootNamespace>ClipForgeAI.Win</RootNamespace>
    <AssemblyName>ClipForge</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>

    <Platforms>x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
    <UseWinUI>true</UseWinUI>
    <EnableMsixTooling>false</EnableMsixTooling>
    <WindowsPackageType>None</WindowsPackageType>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <SelfContained>true</SelfContained>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <PublishReadyToRun>false</PublishReadyToRun>
    <PublishSingleFile>false</PublishSingleFile>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <Product>ClipForge · AI 视频编辑助手</Product>
    <Company>ClipForge</Company>
    <Version>2.0.0</Version>
    <FileVersion>2.0.0.0</FileVersion>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.6.241114003" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22621.756" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
    <!-- YamlDotNet:用于读写 settings.yml 明文配置文件 -->
    <PackageReference Include="YamlDotNet" Version="15.1.6" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\**\*.*" />
  </ItemGroup>

</Project>
